name: Release SDK & UI

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
        env:
          FORCE_COLOR: 0 # Workaround for setup-node issue

      - run: yarn install --immutable
      - run: yarn build

      - name: Test SDK & UI
        run: yarn test

      - name: Test SDK integration against live contracts
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn test-live

      - name: Release SDK on NPM
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Set Docker Image Tag
        run: echo "TAG=$(if [[ '${{ github.ref }}' == 'refs/heads/master' ]]; then echo 'latest'; else echo 'next'; fi)" >> $GITHUB_ENV

      - name: Build and Push dev-frontend Image to Docker Hub
        if: ${{ github.event_name == 'push' }}
        run: |
          docker-compose build
          docker tag liquity/dev-frontend:$TAG shivanshu814/liquity-dev-frontend:$TAG
          docker push shivanshu814/liquity-dev-frontend:$TAG
        working-directory: ./packages/dev-frontend
